sudo: required
dist: trusty

language: cpp

env:
 - QT_SELECT=qt4
 - QT_SELECT=qt5

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libqtgui4 qt4-qmake libqt5widgets5 libqt5svg5-dev qt5-qmake qt5-default qtchooser

script:
 - qmake
 - make
